### ISSUE TITLE
Open Java-Websockify for extension

### ISSUE THREAD

**Issue by youribonnaffe** [jribble/Java-Websockify#3]
Hi,

I'm very happy to use this proxy with noVnc but my use case requires me to act as some sort of dynamic proxy. Ideally I would like the client to specify a hostname + port parameters with the socket connection and then websockify to use these parameters instead of a StaticTargetResolver. 
To achieve that I've made modifications in WebsockifyProxyHandler but I would like to avoid forking the project and maintain a separate fork. 
Would you say this use case could be integrated in Java-Websockify ? Or would you consider opening the code a bit more for extension ?

**Comment by jribble** [comment]
I'm open to considering your code for addition to my repo.  I have two main concerns: 1) the pure VNC protocol has to work and 2) no new security holes.

Prior to using noVNC I actually had developed a similar addition to the VNC protocol that allowed my client to specify where the connection should be proxied.  There were two problems with this: 1) I couldn't use any VNC client but my own and 2) I had to trust the client.  With Java-Websockify, using a custom target resolver I can negotiate where the client is going to connect using a different authenticated channel, then automatically connect the client to that target when the client connects to the proxy.  And I can do it without any change to the VNC protocol so I can use any VNC client software I want.

**Comment by youribonnaffe** [comment]
I don't think my changes affect the VNC protocol itself. To give you an idea, you see my commits here https://github.com/youribonnaffe/Java-Websockify. 
Using a custome target resolver, if I could access the HttpRequest object that would be enough.

I'm also using the "redirect" HTTP path to first connect to the websocket proxy with HTTPs then redirect to a static web page that creatse the secure websocket and connects to the websocket proxy. This is just so the user has a change to accept a certificate.

**Comment by youribonnaffe** [comment]
I misunderstood what you said and looked at the code again. I didn't understand that Java-Websockify was actually compatible with any VNC client, I thought it was only to work with VNC. 
When you say, "using a custom target resolver I can negotiate where the client is going to connect using a different authenticated channel, then automatically connect the client to that target when the client connects to the proxy", how do you retrieve the target in the custom target resolver ? how do you map the VNC/websocket connection with a target that would have been resolved in a "authenticated" channel ?

**Comment by jribble** [comment]
Sorry I've been slow to respond.  I was intending to find some of my code
that uses this to give you an example.  I'm working on that now.

**Comment by jribble** [comment]
Yes, Java-Websockify can act as a proxy for any VNC client.  Our specific
requirement is to support both noVNC and VNC clients on the iPad.  The
PortUnificationHandler figures out if the incoming connection is a plain
VNC connection (DirectProxyHandler), an HTML5 websocket connection
(WebsockifyProxyHandler) or a Flash connection (FlashPolicyHandler, then
WebsockifyProxyHandler).

Okay, the code that I have is pretty specific to the application I'm using
it in.  So I'm just going to give you the general idea here in snippets.

First, you create your own target resolver.  It's going to be given the
inbound channel and from that it's job is to determine the address of the
target to complete the proxy connection.  You can use any logic you want to
figure out the target address.  In my case I'm managing a list of VMs and I
know the person that's logged in and what VMs he's allowed to access.  When
he clicks a button to connect a VNC console to a specific VM I put into a
Map his IP address and the IP address of the VM that he wants to connect
to.  When my websockify server calls resolveTarget on my custom target
resolver I take the source IP address from the inbound channel and I look
up the target in the map.

## So my custom target resolver looks like this:

public class VNCHelper implements IProxyTargetResolver

{

   protected static Map <String, VncConnectionInfoObject> accessControlMap=
new HashMap <String, VncConnectionInfoObject> ();

   protected static VNCHelper instance = new VNCHelper();

   private VNCHelper (){};

   public static VNCHelper getInstance ()

   {

```
  return instance;
```

   }

   @Override

   public InetSocketAddress resolveTarget( Channel channel )

   {

```
  String remoteHost = null;

  SocketAddress sa = channel.getRemoteAddress ( );

  if ( sa instanceof InetSocketAddress )

  {

     InetSocketAddress isa = (InetSocketAddress) sa;

     remoteHost = isa.getAddress ( ).getHostAddress ( );

  }


  if ( remoteHost != null )

  {

     VncConnectionInfoObject vncInfo = testAccess ( remoteHost );

     if ( vncInfo != null )

     {

        return new InetSocketAddress ( vncInfo.getVncIp ( ),
```

vncInfo.getVncPort ( ).intValue ( ) );

```
     }

  }


  return null;
```

   }

}

---

It also has some other methods to manage the access control map.  I pulled
those out for clarity.

When I create my websockify server instance I start it like this:

---

ws = new WebsockifyServer ( );

ws.connect ( port, VNCHelper.getInstance(), enableSSL ? SSLSetting.ON :
SSLSetting.OFF, keystore, ksPassword, kskeyPassword, null );

---

The websockify server will use the custom target resolver to determine the
proxy's target for each incoming connection.

I also have a different case where the websockify proxy server is running
on a different server than my application server.  In that case I use
essentially the same logic, but instead of looking up the target address in
a map in the same JVM space, the custom target resolver makes a REST call
to the application server to ask what the target should be.  That may be a
good example for you.  I'll push it up to a github repo so you can use it
as an example.

**Comment by jribble** [comment]
Okay, you can look at https://github.com/jribble/ExternalVNCRepeater for a
complete example of consuming Java-Websockify to create your own proxy that
uses its own logic to determine the proxy target.

**Comment by youribonnaffe** [comment]
Thanks for all the details.
If users are behind a proxy, or if the same user opens several remote visualization, couldn't it be an issue ?

**Comment by jribble** [comment]
Yes, that could be an issue with my solution.  But my solution is for a
specific use case.  You should be able to modify or expand my solution to
use whatever criteria you want to determine the target.

**Comment by youribonnaffe** [comment]
Ok so I've decided to fork the few classes I'm interested in for my specific use case. I consider my request to be closed. Thanks for your comments.
